In [1]:
import numpy as np
import pandas as pd

## Reading Data

In [2]:

data = pd.read_csv('./time_series.csv')
data

people
0       176
1       351
2       101
3       386
4       199
..      ...
351     597
352     291
353     198
354     439
355     323

[356 rows x 1 columns]

In [3]:
timesteps = data.index.to_numpy()
prices = data["people"].to_numpy()

timesteps[:10], prices[:10]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([176, 351, 101, 386, 199, 356, 299, 144, 418, 594]))

In [4]:

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(timesteps, 
                                                    prices,
                                                    test_size=0.2,
                                                    random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape 

((284,), (72,), (284,), (72,))

In [7]:

split_size = int(0.8 * len(prices)) 

X_train, y_train = timesteps[:split_size], prices[:split_size]

X_test, y_test = timesteps[split_size:], prices[split_size:]

len(X_train), len(X_test), len(y_train), len(y_test)

(284, 72, 284, 72)

## Predictions

In [8]:

naive_forecast = y_test[:-1] 
naive_forecast[:10], naive_forecast[-10:]

(array([112, 125, 512, 502, 207, 315, 186, 544, 595, 328]),
 array([327, 104, 312, 576, 102, 156, 597, 291, 198, 439]))